### ISSUE TITLE
Get all magnet balls by component instead of name

### ISSUE THREAD

**Issue by ARtsiomachka** [yayorbitgum/Escape#1]
In [UMagneticBalls::GetAllMagneticBalls()](https://github.com/yayorbitgum/Escape/blob/4821f2148986249bb5105fc7fa121e4526f6aa83/Source/Escape/MagneticBalls.cpp#L150) you could try fetching actor's UMagneticBalls component to determine whether it's a magnetic ball or not instead of checking its name.

So, instead of
`if (Actor->GetName().StartsWith("MagneticBall") && Actor->GetOwner() == nullptr)`
you can use
`if (Actor->FindComponentByClass<UMagneticBalls>() && Actor->GetOwner() == nullptr)`

**Comment by 7MinutesDead-Git** [comment]
That's much better. Thank you!
https://github.com/yayorbitgum/Escape/commit/68a82b62ef5ba6fca07a7f1e692d0489109fa30d
